import { lazy } from 'react'

/*
 * Every code-split screen, in one place. Extracted from App.tsx (#316).
 * Import paths and `.then()` shapes are unchanged, so the emitted chunk
 * boundaries stay exactly as they were.
 */
export const CardRestSelect = lazy(() => import('../components/cards/CardRestSelect').then(m => ({ default: m.CardRestSelect })))
export const CampScreen = lazy(() => import('../components/campaign/CampScreen').then(m => ({ default: m.CampScreen })))
export const EventScreen = lazy(() => import('../components/campaign/EventScreen').then(m => ({ default: m.EventScreen })))
export const MysteryScreen = lazy(() => import('../components/campaign/MysteryScreen').then(m => ({ default: m.MysteryScreen })))
export const MemoryFragmentScreen = lazy(() => import('../components/campaign/MemoryFragmentScreen').then(m => ({ default: m.MemoryFragmentScreen })))
export const CharacterEncounterScreen = lazy(() => import('../components/campaign/CharacterEncounterScreen').then(m => ({ default: m.CharacterEncounterScreen })))
export const NarratorJournalScreen = lazy(() => import('../components/hub/NarratorJournalScreen').then(m => ({ default: m.NarratorJournalScreen })))
export const CharacterScreen = lazy(() => import('../components/screens/CharacterScreen').then(m => ({ default: m.CharacterScreen })))
export const CutsceneScreen = lazy(() => import('../components/campaign/CutsceneScreen').then(m => ({ default: m.CutsceneScreen })))
export const BossDialogueScreen = lazy(() => import('../components/battle/BossDialogueScreen').then(m => ({ default: m.BossDialogueScreen })))
export const Battlefield = lazy(() => import('../components/battle/Battlefield').then(m => ({ default: m.Battlefield })))
export const GameOver = lazy(() => import('../components/battle/GameOver').then(m => ({ default: m.GameOver })))
export const QuickBattleScreen = lazy(() => import('../components/screens/QuickBattleScreen').then(m => ({ default: m.QuickBattleScreen })))
export const CardDraftScreen = lazy(() => import('../components/screens/CardDraftScreen').then(m => ({ default: m.CardDraftScreen })))
export const CollectionScreen = lazy(() => import('../components/screens/CollectionScreen').then(m => ({ default: m.CollectionScreen })))
export const DeckBuilder = lazy(() => import('../components/cards/DeckBuilder').then(m => ({ default: m.DeckBuilder })))
export const PackOpening = lazy(() => import('../components/cards/PackOpening').then(m => ({ default: m.PackOpening })))
export const HubWorld = lazy(() => import('../components/hub/HubWorld').then(m => ({ default: m.HubWorld })))
export const HubWorldMap = lazy(() => import('../components/hub/HubWorldMap').then(m => ({ default: m.HubWorldMap })))
export const CasinoScreen = lazy(() => import('../components/hub/CasinoScreen').then(m => ({ default: m.CasinoScreen })))
export const FishAppraisalScreen = lazy(() => import('../components/hub/FishAppraisalScreen').then(m => ({ default: m.FishAppraisalScreen })))
export const TheatreScreen = lazy(() => import('../components/hub/TheatreScreen').then(m => ({ default: m.TheatreScreen })))
export const PostBattleReward = lazy(() => import('../components/battle/PostBattleReward').then(m => ({ default: m.PostBattleReward })))
export const ActComplete = lazy(() => import('../components/battle/ActComplete').then(m => ({ default: m.ActComplete })))
export const RelicSelectScreen = lazy(() => import('../components/campaign/RelicSelectScreen').then(m => ({ default: m.RelicSelectScreen })))
export const ReplayBriefingScreen = lazy(() => import('../components/campaign/ReplayBriefingScreen').then(m => ({ default: m.ReplayBriefingScreen })))
export const StarterPackSelect = lazy(() => import('../components/cards/StarterPackSelect').then(m => ({ default: m.StarterPackSelect })))
export const FakeCrashEvent = lazy(() => import('../components/rare-events/FakeCrashEvent').then(m => ({ default: m.FakeCrashEvent })))
export const BlackjackEvent = lazy(() => import('../components/rare-events/BlackjackEvent').then(m => ({ default: m.BlackjackEvent })))
export const WrongNumberEvent = lazy(() => import('../components/rare-events/WrongNumberEvent').then(m => ({ default: m.WrongNumberEvent })))
export const NarratorEvent = lazy(() => import('../components/rare-events/NarratorEvent').then(m => ({ default: m.NarratorEvent })))
export const LiarsDiceEvent = lazy(() => import('../components/rare-events/LiarsDiceEvent').then(m => ({ default: m.LiarsDiceEvent })))
export const GamblerEvent = lazy(() => import('../components/rare-events/GamblerEvent').then(m => ({ default: m.GamblerEvent })))
export const DevBuildEvent = lazy(() => import('../components/rare-events/DevBuildEvent').then(m => ({ default: m.DevBuildEvent })))
export const GlitchedCardEvent = lazy(() => import('../components/rare-events/GlitchedCardEvent').then(m => ({ default: m.GlitchedCardEvent })))
export const ConfusedTouristEvent = lazy(() => import('../components/rare-events/ConfusedTouristEvent').then(m => ({ default: m.ConfusedTouristEvent })))
export const GiftAdminScreen = lazy(() => import('../components/admin/GiftAdminScreen').then(m => ({ default: m.GiftAdminScreen })))
export const InventoryScreen = lazy(() => import('../components/screens/InventoryScreen').then(m => ({ default: m.InventoryScreen })))
export const NewsScreen = lazy(() => import('../components/screens/NewsScreen').then(m => ({ default: m.NewsScreen })))
export const NewsAdminScreen = lazy(() => import('../components/admin/NewsAdminScreen').then(m => ({ default: m.NewsAdminScreen })))
export const CampaignAdminScreen = lazy(() => import('../components/admin/CampaignAdminScreen').then(m => ({ default: m.CampaignAdminScreen })))
export const SceneryAdminScreen = lazy(() => import('../components/admin/SceneryAdminScreen').then(m => ({ default: m.SceneryAdminScreen })))
export const FeedbackAdminScreen = lazy(() => import('../components/admin/FeedbackAdminScreen').then(m => ({ default: m.FeedbackAdminScreen })))
export const TownAccessAdminScreen = lazy(() => import('../components/admin/TownAccessAdminScreen').then(m => ({ default: m.TownAccessAdminScreen })))
export const WeeklyChallengeScreen = lazy(() => import('../components/screens/WeeklyChallengeScreen').then(m => ({ default: m.WeeklyChallengeScreen })))
export const ChronicleScreen = lazy(() => import('../components/screens/ChronicleScreen').then(m => ({ default: m.ChronicleScreen })))
export const BossEpilogueScreen = lazy(() => import('../components/campaign/BossEpilogueScreen').then(m => ({ default: m.BossEpilogueScreen })))
export const CommanderScreen = lazy(() => import('../components/screens/CommanderScreen').then(m => ({ default: m.CommanderScreen })))
export const TrainingScreen = lazy(() => import('../components/screens/TrainingScreen').then(m => ({ default: m.TrainingScreen })))
export const AchievementsScreen = lazy(() => import('../components/screens/AchievementsScreen').then(m => ({ default: m.AchievementsScreen })))
export const HallOfAchievements = lazy(() => import('../components/hub/HallOfAchievements').then(m => ({ default: m.HallOfAchievements })))
export const HomeShelf = lazy(() => import('../components/hub/HomeShelf').then(m => ({ default: m.HomeShelf })))
export const HeroCardsScreen = lazy(() => import('../components/screens/HeroCardsScreen').then(m => ({ default: m.HeroCardsScreen })))
export const FingerSmash = lazy(() => import('../components/battle/FingerSmash'))
export const BossShockwave = lazy(() => import('../components/battle/BossShockwave'))
export const ShopScreen = lazy(() => import('../components/screens/ShopScreen').then(m => ({ default: m.ShopScreen })))
export const BattleSummary = lazy(() => import('../components/battle/BattleSummary').then(m => ({ default: m.BattleSummary })))
export const VictoryPanel = lazy(() => import('../components/battle/VictoryPanel').then(m => ({ default: m.VictoryPanel })))
export const RelicSpinScreen = lazy(() => import('../components/campaign/RelicSpinScreen').then(m => ({ default: m.RelicSpinScreen })))
export const CampaignVictoryScreen = lazy(() => import('../components/battle/CampaignVictoryScreen').then(m => ({ default: m.CampaignVictoryScreen })))
export const ToBeContinuedScreen = lazy(() => import('../components/battle/ToBeContinuedScreen').then(m => ({ default: m.ToBeContinuedScreen })))
export const CampaignFailedScreen = lazy(() => import('../components/battle/CampaignFailedScreen').then(m => ({ default: m.CampaignFailedScreen })))
export const StatUpgradeScreen = lazy(() => import('../components/campaign/StatUpgradeScreen').then(m => ({ default: m.StatUpgradeScreen })))
export const PlayerStatsScreen = lazy(() => import('../components/screens/PlayerStatsScreen').then(m => ({ default: m.PlayerStatsScreen })))
export const CodexScreen = lazy(() => import('../components/screens/CodexScreen').then(m => ({ default: m.CodexScreen })))
export const DailyChallengeScreen = lazy(() => import('../components/screens/DailyChallengeScreen').then(m => ({ default: m.DailyChallengeScreen })))
export const EndlessLeaderboardScreen = lazy(() => import('../components/screens/EndlessLeaderboardScreen').then(m => ({ default: m.EndlessLeaderboardScreen })))
export const MiniGamesMenu = lazy(() => import('../components/screens/MiniGamesMenu').then(m => ({ default: m.MiniGamesMenu })))
export const Fishing = lazy(() => import('../components/minigames/Fishing').then(m => ({ default: m.Fishing })))
export const AugmentCollectionScreen = lazy(() => import('../components/screens/AugmentCollectionScreen').then(m => ({ default: m.AugmentCollectionScreen })))
export const PlayerScreen = lazy(() => import('../components/screens/PlayerScreen').then(m => ({ default: m.PlayerScreen })))
export const CollectionTabScreen = lazy(() => import('../components/screens/CollectionTabScreen').then(m => ({ default: m.CollectionTabScreen })))
